### ISSUE TITLE
Icons not showing on Windows WSL

### ISSUE THREAD

**Issue by vandanrohatgi** [mistakenelf/fm#105]
Terminal: Windows Terminal Version: 1.16.10261.0
WSL: Ubuntu 18.04 LTS
Windows: 10
Installation method: Go install

Icons do not appear in WSL environment.

![image](https://github.com/mistakenelf/fm/assets/43648786/70748da7-7ea4-4bbc-9411-d838684977a3)

**Comment by vandanrohatgi** [comment]
I didn't before but I just installed the [Go Mono](https://www.programmingfonts.org/#go-mono) font. Still not getting the icons.

**Comment by mistakenelf** [comment]
Try installing a font from here https://www.nerdfonts.com/font-downloads

**Comment by vandanrohatgi** [comment]
Yep that's where I installed it from!

**Comment by mistakenelf** [comment]
hmm, not sure why they wouldnt be showing. I unfortunately dont have access to a windows machine to diagnose

**Comment by vandanrohatgi** [comment]
No worries. It's just icons. Everything else is working fine. Please let me know If I can help with debugging using my windows environment. Feel free to close the issue.

**Comment by mistakenelf** [comment]
I’ll leave it open for now and see if I can’t get a hold of a windows machine sometime

**Comment by vandanrohatgi** [comment]
Update: I figured out the issue. Pretty stupid. I was installing nerd fonts in the WSL Linux environment. Instead I had to install them in the system wide windows and them configure them as my default font in Windows terminal.

1. Just download the font of your choice
2. Extract
3. Multi select all the extracted files
4. Right click and then "install for all users"
5. Go to settings in windows terminal
6. Click on "Defaults" under profiles.
7. Additional settings -> Appearance
8. Select installed font in font face setting.
9. Restart terminal
