### ISSUE TITLE
Access help from show states.

### ISSUE THREAD

**Issue by MohamTahaB** [mistakenelf/fm#112]
Hello,

I'm currently exploring repositories that utilize Charm projects, and I stumbled upon FM. It's a wonderful project, offering an elegant solution for navigating and managing files.

However, I noticed that the help section seems to be inaccessible once the state is no longer `idleState`. If this behavior is intentional, I'm wondering if it would be possible to add a key binding that could change the state back to `idleState`  for accessing the help section.

Thanks in advance for considering this suggestion!

**Comment by MohamTahaB** [comment]
OK, looking forward to checking it out !

**Comment by mistakenelf** [comment]
This has merged to main, pressing escape will reset the state and show the help. Wont cut a release for a little bit as there's some stuff that needs cleaned up and fixed
